Make sure apt-add-repository exist

diff --git a/add-apt-ppa b/add-apt-ppa
--- a/add-apt-ppa
+++ b/add-apt-ppa
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if ! type apt-add-repository &> /dev/null; then
+    >&2 echo "apt-add-repository: command not found, try to install package - software-properties-common first!"
+    exit 1
+fi
+
 for para in "$@"
 do
     if [[ "${para}" = "ppa:"* ]];then
